glance_api_config:
    'glance_store/stores':
        value: 'file'
    'glance_store/default_store':
        value: 'file'
nova_config:
    'DEFAULT/verbose':
        value: 'False'

package:
    'git':
        ensure: present
